server:
  servlet:
    context-path: /
  port: '8080'
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
        exclude: ''
    jmx:
      exposure:
        include: '*'
        exclude: ''
  endpoint:
    health:
      probes:
        enabled: 'true'
      show-details: always
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    username: ${MYSQL_USER}
    url: jdbc:mysql://localhost:3306/${MYSQL_DB}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
logging:
  file:
    name: logs/pfe-gitops-demo.log
  level:
    org:
      springframework: 'warn'
    com:
      zaxxer:
        hikari: warn
    root: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %-5level - %logger{60} - %msg%n'