apiVersion: v1
kind: Namespace
metadata:
  name:  gitops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-gitops-demo
  namespace: gitops
  labels:
    app: pfe-gitops-demo
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfe-gitops-demo
      env: dev
  template:
    metadata:
      labels:
        app: pfe-gitops-demo
        env: dev
    spec:
      containers:
      - name: pfe-gitops-demo-app
        image: pfegitops.azurecr.io/pfe-gitops-demo:1.14
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 150M
          limits:
            cpu: 200m
            memory: 300M
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          #runAsNonRoot: true
          #runAsUser: 1000
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
      imagePullSecrets:
          - name:  acr-pull-secret
        

