name: Maven package and publish & cache dependencies

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: "Continous Integration"

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "zulu"
          cache: maven
        
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and force snapshot updates with Maven
        run: |
          mvn -B package --file pom.xml -DskipTests

      - name: Deploy to GitHub Packages
        run: |
          mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    needs: ci
    name: "Continous Integration"

    steps:
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_ACR }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.AZURE_ACR }}/pfe-gitops-demo:${{ github.sha }}
          docker push ${{ secrets.AZURE_ACR }}/pfe-gitops-demo:${{ github.sha }}
